import { MongoClient } from 'mongodb';

const seedData = [
  {"id": "item-1", "name": "Fresh Tomatoes", "category": "Vegetables & Produce", "currentStock": "45", "unit": "kg", "minStock": "10", "costPerUnit": "45", "image": null},
  {"id": "item-2", "name": "Broccoli", "category": "Vegetables & Produce", "currentStock": "30", "unit": "kg", "minStock": "5", "costPerUnit": "80", "image": null},
  {"id": "item-3", "name": "Yellow Onions", "category": "Vegetables & Produce", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "35", "image": null},
  {"id": "item-4", "name": "Garlic", "category": "Vegetables & Produce", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "200", "image": null},
  {"id": "item-5", "name": "Carrots", "category": "Vegetables & Produce", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "40", "image": null},
  {"id": "item-6", "name": "Bell Peppers (Green)", "category": "Vegetables & Produce", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "100", "image": null},
  {"id": "item-7", "name": "Bell Peppers (Red)", "category": "Vegetables & Produce", "currentStock": "20", "unit": "kg", "minStock": "5", "costPerUnit": "120", "image": null},
  {"id": "item-8", "name": "Cabbage", "category": "Vegetables & Produce", "currentStock": "35", "unit": "kg", "minStock": "8", "costPerUnit": "30", "image": null},
  {"id": "item-9", "name": "Spinach", "category": "Vegetables & Produce", "currentStock": "10", "unit": "kg", "minStock": "2", "costPerUnit": "150", "image": null},
  {"id": "item-10", "name": "Cucumber", "category": "Vegetables & Produce", "currentStock": "22", "unit": "kg", "minStock": "5", "costPerUnit": "60", "image": null},
  {"id": "item-11", "name": "Lettuce", "category": "Vegetables & Produce", "currentStock": "18", "unit": "kg", "minStock": "3", "costPerUnit": "70", "image": null},
  {"id": "item-12", "name": "Potatoes", "category": "Vegetables & Produce", "currentStock": "100", "unit": "kg", "minStock": "20", "costPerUnit": "25", "image": null},
  {"id": "item-13", "name": "Sweet Potatoes", "category": "Vegetables & Produce", "currentStock": "30", "unit": "kg", "minStock": "5", "costPerUnit": "50", "image": null},
  {"id": "item-14", "name": "Beetroot", "category": "Vegetables & Produce", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "55", "image": null},
  {"id": "item-15", "name": "Peas (Fresh)", "category": "Vegetables & Produce", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "120", "image": null},
  {"id": "item-16", "name": "Corn", "category": "Vegetables & Produce", "currentStock": "25", "unit": "pcs", "minStock": "5", "costPerUnit": "30", "image": null},
  {"id": "item-17", "name": "Chicken Breast", "category": "Meat & Poultry", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "220", "image": null},
  {"id": "item-18", "name": "Chicken Thighs", "category": "Meat & Poultry", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "180", "image": null},
  {"id": "item-19", "name": "Chicken Whole", "category": "Meat & Poultry", "currentStock": "30", "unit": "kg", "minStock": "5", "costPerUnit": "200", "image": null},
  {"id": "item-20", "name": "Ground Chicken", "category": "Meat & Poultry", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "210", "image": null},
  {"id": "item-21", "name": "Mutton", "category": "Meat & Poultry", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "350", "image": null},
  {"id": "item-22", "name": "Ground Mutton", "category": "Meat & Poultry", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "340", "image": null},
  {"id": "item-23", "name": "Beef Cuts", "category": "Meat & Poultry", "currentStock": "45", "unit": "kg", "minStock": "10", "costPerUnit": "450", "image": null},
  {"id": "item-24", "name": "Ground Beef", "category": "Meat & Poultry", "currentStock": "30", "unit": "kg", "minStock": "6", "costPerUnit": "420", "image": null},
  {"id": "item-25", "name": "Pork Cuts", "category": "Meat & Poultry", "currentStock": "28", "unit": "kg", "minStock": "5", "costPerUnit": "320", "image": null},
  {"id": "item-26", "name": "Turkey Breast", "category": "Meat & Poultry", "currentStock": "22", "unit": "kg", "minStock": "4", "costPerUnit": "280", "image": null},
  {"id": "item-27", "name": "Duck", "category": "Meat & Poultry", "currentStock": "18", "unit": "kg", "minStock": "3", "costPerUnit": "380", "image": null},
  {"id": "item-28", "name": "Sausages", "category": "Meat & Poultry", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "280", "image": null},
  {"id": "item-29", "name": "Bacon", "category": "Meat & Poultry", "currentStock": "12", "unit": "kg", "minStock": "2", "costPerUnit": "500", "image": null},
  {"id": "item-30", "name": "Ham", "category": "Meat & Poultry", "currentStock": "14", "unit": "kg", "minStock": "2", "costPerUnit": "420", "image": null},
  {"id": "item-31", "name": "Salmon Fillet", "category": "Fish & Seafood", "currentStock": "30", "unit": "kg", "minStock": "5", "costPerUnit": "650", "image": null},
  {"id": "item-32", "name": "Pomfret Fish", "category": "Fish & Seafood", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "450", "image": null},
  {"id": "item-33", "name": "Prawns", "category": "Fish & Seafood", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "800", "image": null},
  {"id": "item-34", "name": "Crab", "category": "Fish & Seafood", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "900", "image": null},
  {"id": "item-35", "name": "Squid", "category": "Fish & Seafood", "currentStock": "18", "unit": "kg", "minStock": "3", "costPerUnit": "500", "image": null},
  {"id": "item-36", "name": "Mackerel", "category": "Fish & Seafood", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "280", "image": null},
  {"id": "item-37", "name": "Tuna", "category": "Fish & Seafood", "currentStock": "28", "unit": "kg", "minStock": "5", "costPerUnit": "550", "image": null},
  {"id": "item-38", "name": "Cod Fish", "category": "Fish & Seafood", "currentStock": "22", "unit": "kg", "minStock": "4", "costPerUnit": "480", "image": null},
  {"id": "item-39", "name": "Rohu Fish", "category": "Fish & Seafood", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "320", "image": null},
  {"id": "item-40", "name": "Catfish", "category": "Fish & Seafood", "currentStock": "32", "unit": "kg", "minStock": "6", "costPerUnit": "280", "image": null},
  {"id": "item-41", "name": "Mozzarella Cheese", "category": "Dairy & Cheese", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "580", "image": null},
  {"id": "item-42", "name": "Cheddar Cheese", "category": "Dairy & Cheese", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "650", "image": null},
  {"id": "item-43", "name": "Paneer", "category": "Dairy & Cheese", "currentStock": "30", "unit": "kg", "minStock": "5", "costPerUnit": "380", "image": null},
  {"id": "item-44", "name": "Milk (Full Cream)", "category": "Dairy & Cheese", "currentStock": "100", "unit": "L", "minStock": "20", "costPerUnit": "65", "image": null},
  {"id": "item-45", "name": "Milk (Low Fat)", "category": "Dairy & Cheese", "currentStock": "80", "unit": "L", "minStock": "15", "costPerUnit": "60", "image": null},
  {"id": "item-46", "name": "Yogurt", "category": "Dairy & Cheese", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "120", "image": null},
  {"id": "item-47", "name": "Butter", "category": "Dairy & Cheese", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "480", "image": null},
  {"id": "item-48", "name": "Ghee (Clarified Butter)", "category": "Dairy & Cheese", "currentStock": "28", "unit": "kg", "minStock": "5", "costPerUnit": "550", "image": null},
  {"id": "item-49", "name": "Cream", "category": "Dairy & Cheese", "currentStock": "20", "unit": "L", "minStock": "4", "costPerUnit": "280", "image": null},
  {"id": "item-50", "name": "Feta Cheese", "category": "Dairy & Cheese", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "620", "image": null},
  {"id": "item-51", "name": "White Bread", "category": "Bakery & Bread", "currentStock": "50", "unit": "pcs", "minStock": "10", "costPerUnit": "40", "image": null},
  {"id": "item-52", "name": "Brown Bread", "category": "Bakery & Bread", "currentStock": "45", "unit": "pcs", "minStock": "9", "costPerUnit": "50", "image": null},
  {"id": "item-53", "name": "Baguette", "category": "Bakery & Bread", "currentStock": "30", "unit": "pcs", "minStock": "6", "costPerUnit": "80", "image": null},
  {"id": "item-54", "name": "Croissants", "category": "Bakery & Bread", "currentStock": "25", "unit": "pcs", "minStock": "5", "costPerUnit": "50", "image": null},
  {"id": "item-55", "name": "Focaccia Bread", "category": "Bakery & Bread", "currentStock": "20", "unit": "pcs", "minStock": "4", "costPerUnit": "75", "image": null},
  {"id": "item-56", "name": "Sourdough Bread", "category": "Bakery & Bread", "currentStock": "22", "unit": "pcs", "minStock": "4", "costPerUnit": "85", "image": null},
  {"id": "item-57", "name": "Rye Bread", "category": "Bakery & Bread", "currentStock": "18", "unit": "pcs", "minStock": "3", "costPerUnit": "70", "image": null},
  {"id": "item-58", "name": "Whole Wheat Bread", "category": "Bakery & Bread", "currentStock": "28", "unit": "pcs", "minStock": "5", "costPerUnit": "55", "image": null},
  {"id": "item-59", "name": "Pita Bread", "category": "Bakery & Bread", "currentStock": "35", "unit": "pcs", "minStock": "7", "costPerUnit": "35", "image": null},
  {"id": "item-60", "name": "Naan Bread", "category": "Bakery & Bread", "currentStock": "40", "unit": "pcs", "minStock": "8", "costPerUnit": "40", "image": null},
  {"id": "item-61", "name": "Spaghetti Pasta", "category": "Grains & Pasta", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "120", "image": null},
  {"id": "item-62", "name": "Penne Pasta", "category": "Grains & Pasta", "currentStock": "45", "unit": "kg", "minStock": "9", "costPerUnit": "130", "image": null},
  {"id": "item-63", "name": "Fusilli Pasta", "category": "Grains & Pasta", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "125", "image": null},
  {"id": "item-64", "name": "Rice (Basmati)", "category": "Grains & Pasta", "currentStock": "100", "unit": "kg", "minStock": "20", "costPerUnit": "90", "image": null},
  {"id": "item-65", "name": "Rice (White)", "category": "Grains & Pasta", "currentStock": "80", "unit": "kg", "minStock": "15", "costPerUnit": "70", "image": null},
  {"id": "item-66", "name": "Rice (Brown)", "category": "Grains & Pasta", "currentStock": "60", "unit": "kg", "minStock": "12", "costPerUnit": "85", "image": null},
  {"id": "item-67", "name": "Couscous", "category": "Grains & Pasta", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "180", "image": null},
  {"id": "item-68", "name": "Quinoa", "category": "Grains & Pasta", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "280", "image": null},
  {"id": "item-69", "name": "Wheat Flour", "category": "Grains & Pasta", "currentStock": "100", "unit": "kg", "minStock": "20", "costPerUnit": "45", "image": null},
  {"id": "item-70", "name": "Rice Flour", "category": "Grains & Pasta", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "70", "image": null},
  {"id": "item-71", "name": "Olive Oil", "category": "Oils & Condiments", "currentStock": "40", "unit": "L", "minStock": "8", "costPerUnit": "450", "image": null},
  {"id": "item-72", "name": "Vegetable Oil", "category": "Oils & Condiments", "currentStock": "60", "unit": "L", "minStock": "12", "costPerUnit": "180", "image": null},
  {"id": "item-73", "name": "Coconut Oil", "category": "Oils & Condiments", "currentStock": "35", "unit": "L", "minStock": "7", "costPerUnit": "280", "image": null},
  {"id": "item-74", "name": "Sesame Oil", "category": "Oils & Condiments", "currentStock": "20", "unit": "L", "minStock": "4", "costPerUnit": "580", "image": null},
  {"id": "item-75", "name": "Mustard Oil", "category": "Oils & Condiments", "currentStock": "45", "unit": "L", "minStock": "9", "costPerUnit": "220", "image": null},
  {"id": "item-76", "name": "Vinegar (White)", "category": "Oils & Condiments", "currentStock": "30", "unit": "L", "minStock": "6", "costPerUnit": "100", "image": null},
  {"id": "item-77", "name": "Vinegar (Balsamic)", "category": "Oils & Condiments", "currentStock": "20", "unit": "L", "minStock": "4", "costPerUnit": "450", "image": null},
  {"id": "item-78", "name": "Soy Sauce", "category": "Oils & Condiments", "currentStock": "25", "unit": "L", "minStock": "5", "costPerUnit": "200", "image": null},
  {"id": "item-79", "name": "Worcestershire Sauce", "category": "Oils & Condiments", "currentStock": "22", "unit": "L", "minStock": "4", "costPerUnit": "280", "image": null},
  {"id": "item-80", "name": "Hot Sauce", "category": "Oils & Condiments", "currentStock": "18", "unit": "L", "minStock": "3", "costPerUnit": "180", "image": null},
  {"id": "item-81", "name": "Turmeric Powder", "category": "Spices & Seasonings", "currentStock": "8", "unit": "kg", "minStock": "2", "costPerUnit": "280", "image": null},
  {"id": "item-82", "name": "Chili Powder", "category": "Spices & Seasonings", "currentStock": "7", "unit": "kg", "minStock": "2", "costPerUnit": "320", "image": null},
  {"id": "item-83", "name": "Cumin Seeds", "category": "Spices & Seasonings", "currentStock": "6", "unit": "kg", "minStock": "1.5", "costPerUnit": "380", "image": null},
  {"id": "item-84", "name": "Coriander Powder", "category": "Spices & Seasonings", "currentStock": "8", "unit": "kg", "minStock": "2", "costPerUnit": "320", "image": null},
  {"id": "item-85", "name": "Black Pepper", "category": "Spices & Seasonings", "currentStock": "5", "unit": "kg", "minStock": "1", "costPerUnit": "600", "image": null},
  {"id": "item-86", "name": "Garam Masala", "category": "Spices & Seasonings", "currentStock": "6", "unit": "kg", "minStock": "1.5", "costPerUnit": "420", "image": null},
  {"id": "item-87", "name": "Cinnamon", "category": "Spices & Seasonings", "currentStock": "4", "unit": "kg", "minStock": "1", "costPerUnit": "880", "image": null},
  {"id": "item-88", "name": "Cardamom", "category": "Spices & Seasonings", "currentStock": "3", "unit": "kg", "minStock": "0.5", "costPerUnit": "1200", "image": null},
  {"id": "item-89", "name": "Cloves", "category": "Spices & Seasonings", "currentStock": "2", "unit": "kg", "minStock": "0.5", "costPerUnit": "1400", "image": null},
  {"id": "item-90", "name": "Nutmeg", "category": "Spices & Seasonings", "currentStock": "3", "unit": "kg", "minStock": "0.5", "costPerUnit": "1100", "image": null},
  {"id": "item-91", "name": "Coca Cola", "category": "Beverages", "currentStock": "150", "unit": "pcs", "minStock": "30", "costPerUnit": "30", "image": null},
  {"id": "item-92", "name": "Fanta Orange", "category": "Beverages", "currentStock": "120", "unit": "pcs", "minStock": "25", "costPerUnit": "28", "image": null},
  {"id": "item-93", "name": "Sprite", "category": "Beverages", "currentStock": "100", "unit": "pcs", "minStock": "20", "costPerUnit": "30", "image": null},
  {"id": "item-94", "name": "Water Bottles", "category": "Beverages", "currentStock": "200", "unit": "pcs", "minStock": "40", "costPerUnit": "15", "image": null},
  {"id": "item-95", "name": "Orange Juice", "category": "Beverages", "currentStock": "60", "unit": "L", "minStock": "12", "costPerUnit": "180", "image": null},
  {"id": "item-96", "name": "Apple Juice", "category": "Beverages", "currentStock": "55", "unit": "L", "minStock": "10", "costPerUnit": "170", "image": null},
  {"id": "item-97", "name": "Cranberry Juice", "category": "Beverages", "currentStock": "40", "unit": "L", "minStock": "8", "costPerUnit": "220", "image": null},
  {"id": "item-98", "name": "Lemonade", "category": "Beverages", "currentStock": "45", "unit": "L", "minStock": "9", "costPerUnit": "120", "image": null},
  {"id": "item-99", "name": "Iced Tea", "category": "Beverages", "currentStock": "50", "unit": "L", "minStock": "10", "costPerUnit": "100", "image": null},
  {"id": "item-100", "name": "Kombucha", "category": "Beverages", "currentStock": "35", "unit": "L", "minStock": "7", "costPerUnit": "280", "image": null},
  {"id": "item-101", "name": "Apples", "category": "Fruits", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "120", "image": null},
  {"id": "item-102", "name": "Bananas", "category": "Fruits", "currentStock": "60", "unit": "kg", "minStock": "12", "costPerUnit": "50", "image": null},
  {"id": "item-103", "name": "Oranges", "category": "Fruits", "currentStock": "45", "unit": "kg", "minStock": "9", "costPerUnit": "100", "image": null},
  {"id": "item-104", "name": "Grapes", "category": "Fruits", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "180", "image": null},
  {"id": "item-105", "name": "Strawberries", "category": "Fruits", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "280", "image": null},
  {"id": "item-106", "name": "Blueberries", "category": "Fruits", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "420", "image": null},
  {"id": "item-107", "name": "Mangoes", "category": "Fruits", "currentStock": "55", "unit": "kg", "minStock": "11", "costPerUnit": "140", "image": null},
  {"id": "item-108", "name": "Pineapples", "category": "Fruits", "currentStock": "30", "unit": "pcs", "minStock": "6", "costPerUnit": "80", "image": null},
  {"id": "item-109", "name": "Watermelon", "category": "Fruits", "currentStock": "25", "unit": "pcs", "minStock": "5", "costPerUnit": "120", "image": null},
  {"id": "item-110", "name": "Lemons", "category": "Fruits", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "80", "image": null},
  {"id": "item-111", "name": "Frozen Vegetables Mix", "category": "Frozen Items", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "180", "image": null},
  {"id": "item-112", "name": "Frozen Peas", "category": "Frozen Items", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "160", "image": null},
  {"id": "item-113", "name": "Frozen Corn", "category": "Frozen Items", "currentStock": "30", "unit": "kg", "minStock": "6", "costPerUnit": "150", "image": null},
  {"id": "item-114", "name": "Frozen Berries", "category": "Frozen Items", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "350", "image": null},
  {"id": "item-115", "name": "Frozen Chicken Breast", "category": "Frozen Items", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "200", "image": null},
  {"id": "item-116", "name": "Frozen Fish Fillets", "category": "Frozen Items", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "580", "image": null},
  {"id": "item-117", "name": "Frozen Shrimp", "category": "Frozen Items", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "650", "image": null},
  {"id": "item-118", "name": "Frozen Pizza", "category": "Frozen Items", "currentStock": "30", "unit": "pcs", "minStock": "5", "costPerUnit": "280", "image": null},
  {"id": "item-119", "name": "Frozen Fries", "category": "Frozen Items", "currentStock": "45", "unit": "kg", "minStock": "9", "costPerUnit": "120", "image": null},
  {"id": "item-120", "name": "Ice Cream", "category": "Frozen Items", "currentStock": "50", "unit": "L", "minStock": "10", "costPerUnit": "200", "image": null},
  {"id": "item-121", "name": "Canned Tomatoes", "category": "Canned & Packaged", "currentStock": "60", "unit": "pcs", "minStock": "12", "costPerUnit": "85", "image": null},
  {"id": "item-122", "name": "Canned Beans", "category": "Canned & Packaged", "currentStock": "50", "unit": "pcs", "minStock": "10", "costPerUnit": "70", "image": null},
  {"id": "item-123", "name": "Canned Corn", "category": "Canned & Packaged", "currentStock": "45", "unit": "pcs", "minStock": "9", "costPerUnit": "65", "image": null},
  {"id": "item-124", "name": "Canned Peas", "category": "Canned & Packaged", "currentStock": "40", "unit": "pcs", "minStock": "8", "costPerUnit": "60", "image": null},
  {"id": "item-125", "name": "Canned Pineapple", "category": "Canned & Packaged", "currentStock": "35", "unit": "pcs", "minStock": "7", "costPerUnit": "90", "image": null},
  {"id": "item-126", "name": "Canned Peaches", "category": "Canned & Packaged", "currentStock": "30", "unit": "pcs", "minStock": "6", "costPerUnit": "85", "image": null},
  {"id": "item-127", "name": "Canned Tuna", "category": "Canned & Packaged", "currentStock": "50", "unit": "pcs", "minStock": "10", "costPerUnit": "110", "image": null},
  {"id": "item-128", "name": "Canned Salmon", "category": "Canned & Packaged", "currentStock": "35", "unit": "pcs", "minStock": "7", "costPerUnit": "140", "image": null},
  {"id": "item-129", "name": "Canned Chickpeas", "category": "Canned & Packaged", "currentStock": "40", "unit": "pcs", "minStock": "8", "costPerUnit": "75", "image": null},
  {"id": "item-130", "name": "Canned Lentils", "category": "Canned & Packaged", "currentStock": "38", "unit": "pcs", "minStock": "7", "costPerUnit": "80", "image": null},
  {"id": "item-131", "name": "Tomato Sauce", "category": "Sauces & Dressings", "currentStock": "35", "unit": "L", "minStock": "7", "costPerUnit": "120", "image": null},
  {"id": "item-132", "name": "Pesto Sauce", "category": "Sauces & Dressings", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "280", "image": null},
  {"id": "item-133", "name": "Marinara Sauce", "category": "Sauces & Dressings", "currentStock": "28", "unit": "L", "minStock": "5", "costPerUnit": "140", "image": null},
  {"id": "item-134", "name": "Alfredo Sauce", "category": "Sauces & Dressings", "currentStock": "22", "unit": "L", "minStock": "4", "costPerUnit": "180", "image": null},
  {"id": "item-135", "name": "Curry Paste", "category": "Sauces & Dressings", "currentStock": "18", "unit": "kg", "minStock": "3", "costPerUnit": "200", "image": null},
  {"id": "item-136", "name": "Thai Green Curry", "category": "Sauces & Dressings", "currentStock": "16", "unit": "kg", "minStock": "3", "costPerUnit": "220", "image": null},
  {"id": "item-137", "name": "Barbecue Sauce", "category": "Sauces & Dressings", "currentStock": "25", "unit": "L", "minStock": "5", "costPerUnit": "130", "image": null},
  {"id": "item-138", "name": "Teriyaki Sauce", "category": "Sauces & Dressings", "currentStock": "20", "unit": "L", "minStock": "4", "costPerUnit": "160", "image": null},
  {"id": "item-139", "name": "Caesar Dressing", "category": "Sauces & Dressings", "currentStock": "18", "unit": "L", "minStock": "3", "costPerUnit": "180", "image": null},
  {"id": "item-140", "name": "Ranch Dressing", "category": "Sauces & Dressings", "currentStock": "22", "unit": "L", "minStock": "4", "costPerUnit": "150", "image": null},
  {"id": "item-141", "name": "Sugar (White)", "category": "Sugar & Sweeteners", "currentStock": "80", "unit": "kg", "minStock": "16", "costPerUnit": "50", "image": null},
  {"id": "item-142", "name": "Brown Sugar", "category": "Sugar & Sweeteners", "currentStock": "50", "unit": "kg", "minStock": "10", "costPerUnit": "70", "image": null},
  {"id": "item-143", "name": "Honey", "category": "Sugar & Sweeteners", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "320", "image": null},
  {"id": "item-144", "name": "Maple Syrup", "category": "Sugar & Sweeteners", "currentStock": "20", "unit": "L", "minStock": "4", "costPerUnit": "400", "image": null},
  {"id": "item-145", "name": "Corn Syrup", "category": "Sugar & Sweeteners", "currentStock": "25", "unit": "L", "minStock": "5", "costPerUnit": "180", "image": null},
  {"id": "item-146", "name": "Agave Syrup", "category": "Sugar & Sweeteners", "currentStock": "18", "unit": "L", "minStock": "3", "costPerUnit": "280", "image": null},
  {"id": "item-147", "name": "Stevia", "category": "Sugar & Sweeteners", "currentStock": "12", "unit": "kg", "minStock": "2", "costPerUnit": "600", "image": null},
  {"id": "item-148", "name": "Aspartame", "category": "Sugar & Sweeteners", "currentStock": "10", "unit": "kg", "minStock": "2", "costPerUnit": "800", "image": null},
  {"id": "item-149", "name": "Sucralose", "category": "Sugar & Sweeteners", "currentStock": "8", "unit": "kg", "minStock": "1.5", "costPerUnit": "1000", "image": null},
  {"id": "item-150", "name": "Molasses", "category": "Sugar & Sweeteners", "currentStock": "22", "unit": "L", "minStock": "4", "costPerUnit": "200", "image": null},
  {"id": "item-151", "name": "Coffee Beans (Arabica)", "category": "Coffee & Tea", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "480", "image": null},
  {"id": "item-152", "name": "Coffee Beans (Robusta)", "category": "Coffee & Tea", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "350", "image": null},
  {"id": "item-153", "name": "Ground Coffee", "category": "Coffee & Tea", "currentStock": "30", "unit": "kg", "minStock": "6", "costPerUnit": "420", "image": null},
  {"id": "item-154", "name": "Instant Coffee", "category": "Coffee & Tea", "currentStock": "22", "unit": "kg", "minStock": "4", "costPerUnit": "580", "image": null},
  {"id": "item-155", "name": "Black Tea", "category": "Coffee & Tea", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "280", "image": null},
  {"id": "item-156", "name": "Green Tea", "category": "Coffee & Tea", "currentStock": "18", "unit": "kg", "minStock": "3", "costPerUnit": "320", "image": null},
  {"id": "item-157", "name": "White Tea", "category": "Coffee & Tea", "currentStock": "14", "unit": "kg", "minStock": "3", "costPerUnit": "420", "image": null},
  {"id": "item-158", "name": "Herbal Tea", "category": "Coffee & Tea", "currentStock": "16", "unit": "kg", "minStock": "3", "costPerUnit": "350", "image": null},
  {"id": "item-159", "name": "Chamomile Tea", "category": "Coffee & Tea", "currentStock": "12", "unit": "kg", "minStock": "2", "costPerUnit": "380", "image": null},
  {"id": "item-160", "name": "Peppermint Tea", "category": "Coffee & Tea", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "360", "image": null},
  {"id": "item-161", "name": "Chicken Eggs (White)", "category": "Eggs", "currentStock": "500", "unit": "pcs", "minStock": "100", "costPerUnit": "6", "image": null},
  {"id": "item-162", "name": "Chicken Eggs (Brown)", "category": "Eggs", "currentStock": "450", "unit": "pcs", "minStock": "90", "costPerUnit": "7", "image": null},
  {"id": "item-163", "name": "Organic Eggs", "category": "Eggs", "currentStock": "300", "unit": "pcs", "minStock": "60", "costPerUnit": "10", "image": null},
  {"id": "item-164", "name": "Duck Eggs", "category": "Eggs", "currentStock": "150", "unit": "pcs", "minStock": "30", "costPerUnit": "12", "image": null},
  {"id": "item-165", "name": "Quail Eggs", "category": "Eggs", "currentStock": "200", "unit": "pcs", "minStock": "40", "costPerUnit": "15", "image": null},
  {"id": "item-166", "name": "Turkey Eggs", "category": "Eggs", "currentStock": "100", "unit": "pcs", "minStock": "20", "costPerUnit": "18", "image": null},
  {"id": "item-167", "name": "Goose Eggs", "category": "Eggs", "currentStock": "80", "unit": "pcs", "minStock": "15", "costPerUnit": "20", "image": null},
  {"id": "item-168", "name": "Egg Whites (Liquid)", "category": "Eggs", "currentStock": "50", "unit": "L", "minStock": "10", "costPerUnit": "200", "image": null},
  {"id": "item-169", "name": "Egg Yolks (Liquid)", "category": "Eggs", "currentStock": "50", "unit": "L", "minStock": "10", "costPerUnit": "250", "image": null},
  {"id": "item-170", "name": "Powdered Eggs", "category": "Eggs", "currentStock": "15", "unit": "kg", "minStock": "3", "costPerUnit": "800", "image": null},
  {"id": "item-171", "name": "Almonds", "category": "Nuts & Seeds", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "700", "image": null},
  {"id": "item-172", "name": "Cashews", "category": "Nuts & Seeds", "currentStock": "18", "unit": "kg", "minStock": "3", "costPerUnit": "800", "image": null},
  {"id": "item-173", "name": "Walnuts", "category": "Nuts & Seeds", "currentStock": "16", "unit": "kg", "minStock": "3", "costPerUnit": "650", "image": null},
  {"id": "item-174", "name": "Pistachios", "category": "Nuts & Seeds", "currentStock": "14", "unit": "kg", "minStock": "2.5", "costPerUnit": "900", "image": null},
  {"id": "item-175", "name": "Pecans", "category": "Nuts & Seeds", "currentStock": "12", "unit": "kg", "minStock": "2", "costPerUnit": "750", "image": null},
  {"id": "item-176", "name": "Macadamia Nuts", "category": "Nuts & Seeds", "currentStock": "10", "unit": "kg", "minStock": "2", "costPerUnit": "1100", "image": null},
  {"id": "item-177", "name": "Sunflower Seeds", "category": "Nuts & Seeds", "currentStock": "22", "unit": "kg", "minStock": "4", "costPerUnit": "280", "image": null},
  {"id": "item-178", "name": "Pumpkin Seeds", "category": "Nuts & Seeds", "currentStock": "20", "unit": "kg", "minStock": "4", "costPerUnit": "320", "image": null},
  {"id": "item-179", "name": "Flax Seeds", "category": "Nuts & Seeds", "currentStock": "16", "unit": "kg", "minStock": "3", "costPerUnit": "380", "image": null},
  {"id": "item-180", "name": "Chia Seeds", "category": "Nuts & Seeds", "currentStock": "14", "unit": "kg", "minStock": "2", "costPerUnit": "480", "image": null},
  {"id": "item-181", "name": "Basil", "category": "Herbs & Aromatics", "currentStock": "5", "unit": "kg", "minStock": "1", "costPerUnit": "200", "image": null},
  {"id": "item-182", "name": "Parsley", "category": "Herbs & Aromatics", "currentStock": "6", "unit": "kg", "minStock": "1", "costPerUnit": "180", "image": null},
  {"id": "item-183", "name": "Cilantro", "category": "Herbs & Aromatics", "currentStock": "5.5", "unit": "kg", "minStock": "1", "costPerUnit": "190", "image": null},
  {"id": "item-184", "name": "Rosemary", "category": "Herbs & Aromatics", "currentStock": "4", "unit": "kg", "minStock": "0.8", "costPerUnit": "320", "image": null},
  {"id": "item-185", "name": "Thyme", "category": "Herbs & Aromatics", "currentStock": "4", "unit": "kg", "minStock": "0.8", "costPerUnit": "300", "image": null},
  {"id": "item-186", "name": "Oregano", "category": "Herbs & Aromatics", "currentStock": "3.5", "unit": "kg", "minStock": "0.7", "costPerUnit": "280", "image": null},
  {"id": "item-187", "name": "Mint", "category": "Herbs & Aromatics", "currentStock": "5", "unit": "kg", "minStock": "1", "costPerUnit": "220", "image": null},
  {"id": "item-188", "name": "Dill", "category": "Herbs & Aromatics", "currentStock": "3", "unit": "kg", "minStock": "0.6", "costPerUnit": "250", "image": null},
  {"id": "item-189", "name": "Chives", "category": "Herbs & Aromatics", "currentStock": "2.5", "unit": "kg", "minStock": "0.5", "costPerUnit": "280", "image": null},
  {"id": "item-190", "name": "Tarragon", "category": "Herbs & Aromatics", "currentStock": "2", "unit": "kg", "minStock": "0.4", "costPerUnit": "350", "image": null},
  {"id": "item-191", "name": "Lentils (Red)", "category": "Dry Goods", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "120", "image": null},
  {"id": "item-192", "name": "Lentils (Green)", "category": "Dry Goods", "currentStock": "38", "unit": "kg", "minStock": "7", "costPerUnit": "130", "image": null},
  {"id": "item-193", "name": "Chickpeas", "category": "Dry Goods", "currentStock": "45", "unit": "kg", "minStock": "9", "costPerUnit": "110", "image": null},
  {"id": "item-194", "name": "Black Beans", "category": "Dry Goods", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "100", "image": null},
  {"id": "item-195", "name": "Pinto Beans", "category": "Dry Goods", "currentStock": "40", "unit": "kg", "minStock": "8", "costPerUnit": "95", "image": null},
  {"id": "item-196", "name": "Kidney Beans", "category": "Dry Goods", "currentStock": "38", "unit": "kg", "minStock": "7", "costPerUnit": "105", "image": null},
  {"id": "item-197", "name": "Split Peas", "category": "Dry Goods", "currentStock": "32", "unit": "kg", "minStock": "6", "costPerUnit": "140", "image": null},
  {"id": "item-198", "name": "Barley", "category": "Dry Goods", "currentStock": "30", "unit": "kg", "minStock": "6", "costPerUnit": "80", "image": null},
  {"id": "item-199", "name": "Millet", "category": "Dry Goods", "currentStock": "25", "unit": "kg", "minStock": "5", "costPerUnit": "100", "image": null},
  {"id": "item-200", "name": "Buckwheat", "category": "Dry Goods", "currentStock": "22", "unit": "kg", "minStock": "4", "costPerUnit": "120", "image": null},
  {"id": "item-201", "name": "Mung Beans", "category": "Dry Goods", "currentStock": "28", "unit": "kg", "minStock": "5", "costPerUnit": "160", "image": null},
  {"id": "item-202", "name": "Black-Eyed Peas", "category": "Dry Goods", "currentStock": "26", "unit": "kg", "minStock": "5", "costPerUnit": "115", "image": null},
  {"id": "item-203", "name": "Fava Beans", "category": "Dry Goods", "currentStock": "24", "unit": "kg", "minStock": "4", "costPerUnit": "125", "image": null},
  {"id": "item-204", "name": "White Beans", "category": "Dry Goods", "currentStock": "35", "unit": "kg", "minStock": "7", "costPerUnit": "110", "image": null},
  {"id": "item-205", "name": "Cinnamon Sticks", "category": "Spices & Seasonings", "currentStock": "3.5", "unit": "kg", "minStock": "0.7", "costPerUnit": "920", "image": null},
  {"id": "item-206", "name": "Vanilla Beans", "category": "Spices & Seasonings", "currentStock": "2", "unit": "kg", "minStock": "0.4", "costPerUnit": "2400", "image": null}
];

async function seedDatabase() {
  const mongoUrl = process.env.MONGODB_URI || 'mongodb://localhost:27017/pos_system';
  const client = new MongoClient(mongoUrl);
  
  try {
    await client.connect();
    console.log('Connected to MongoDB');
    
    const db = client.db();
    const inventoryCollection = db.collection('inventory');
    
    // Clear existing items
    await inventoryCollection.deleteMany({});
    console.log('Cleared existing inventory');
    
    // Insert all items
    const result = await inventoryCollection.insertMany(seedData);
    console.log(`✓ Inserted ${result.insertedCount} items`);
    
    // Get summary
    const summary = await inventoryCollection.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 }, total: { $sum: { $multiply: [{ $toDouble: '$currentStock' }, { $toDouble: '$costPerUnit' }] } } } },
      { $sort: { _id: 1 } }
    ]).toArray();
    
    console.log('\n✓ Inventory Summary:');
    let totalItems = 0;
    let totalValue = 0;
    summary.forEach(cat => {
      console.log(`  ${cat._id}: ${cat.count} items, Value: ₹${cat.total?.toFixed(2) || '0.00'}`);
      totalItems += cat.count;
      totalValue += cat.total || 0;
    });
    
    console.log(`\nTotal: ${totalItems} items, Total Value: ₹${totalValue.toFixed(2)}`);
    
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await client.close();
  }
}

seedDatabase();
